### ISSUE TITLE
fatal error: 'cxxabi.h' file not found

### ISSUE THREAD

**Issue by sidr16** [LibertyGlobal/flutter-tvos-demo#7]
Hello,
When running ninja_build.sh gives this error

host: arm64
ninja: Entering directory `out/ios_debug_sim_unopt_arm64'
[4/5714] CXX obj/flutter/fml/fml.backtrace.o
FAILED: obj/flutter/fml/fml.backtrace.o 
clang++ -MD -MF obj/flutter/fml/fml.backtrace.o.d -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D_FORTIFY_SOURCE=2 -D_LIBCPP_DISABLE_VISIBILITY_ANNOTATIONS -D_LIBCPP_ENABLE_THREAD_SAFETY_ANNOTATIONS -D_DEBUG -DU_USING_ICU_NAMESPACE=0 -DU_ENABLE_DYLOAD=0 -DUSE_CHROMIUM_ICU=1 -DU_ENABLE_TRACING=1 -DU_ENABLE_RESOURCE_TRACING=0 -DU_STATIC_IMPLEMENTATION -DICU_UTIL_DATA_IMPL=ICU_UTIL_DATA_FILE -DFLUTTER_RUNTIME_MODE_DEBUG=1 -DFLUTTER_RUNTIME_MODE_PROFILE=2 -DFLUTTER_RUNTIME_MODE_RELEASE=3 -DFLUTTER_RUNTIME_MODE_JIT_RELEASE=4 -DDART_LEGACY_API=\[\[deprecated\]\] -DFLUTTER_RUNTIME_MODE=1 -DFLUTTER_JIT_RUNTIME=1 -I../.. -Igen -I../../third_party/icu/source/common -I../../third_party/icu/source/i18n -I../../third_party/dart/runtime -I../../third_party/dart/runtime/include -I../../third_party/abseil-cpp -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/AppleTVSimulator.platform/Developer/SDKs/AppleTVSimulator16.4.sdk -mappletvsimulator-version-min=12.0 -fno-strict-aliasing -arch arm64 -fcolor-diagnostics -Wall -Wextra -Wendif-labels -Werror -Wno-missing-field-initializers -Wno-unused-parameter -Wunguarded-availability -Wno-deprecated-declarations -fvisibility=hidden -stdlib=libc++ -Wstring-conversion -Wnewline-eof -O0 -g2 -fvisibility-inlines-hidden -std=c++17 -fno-rtti -fno-exceptions -nostdinc++ -isystem /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1  -c ../../flutter/fml/backtrace.cc -o obj/flutter/fml/fml.backtrace.o
../../flutter/fml/backtrace.cc:21:10: fatal error: 'cxxabi.h' file not found
#include <cxxabi.h>
         ^~~~~~~~~~
1 error generated.
[15/5714] CXX obj/flutter/impeller/renderer/renderer.command_buffer.o
ninja: build stopped: subcommand failed.

how can  fix this error?

**Comment by jwoelke** [comment]
We have seen this with newer xcode versions and unfortunately have no solution for this yet and are looking into this.
Xcode does no longer include the all the include paths in the dependencies. As a temporary workaround we copied the header files to fix the error

**Comment by kzietek** [comment]
@jwoelke can you describe your workaround in a bit more detail? 

I'm not proficient enough with C++ build systems. Within XCode there are multiple `cxxabi.h` files depending on the platform. Assuming I pick the right one, where should I put it or what should I edit?

As an alternative, on which XCode version did it work?

edit: 
problem was introduced in XCode 14.3, I created some symlinks and it worked:
```
cd /Applications/Xcode.app/Contents/Developer/Platforms/AppleTVSimulator.platform/Developer/SDKs/AppleTVSimulator16.4.sdk/usr/include
ln -s c++/v1/cxxabi.h
ln -s c++/v1/__cxxabi_config.h
cd /Applications/Xcode.app/Contents/Developer/Platforms/AppleTVOS.platform/Developer/SDKs/AppleTVOS16.4.sdk/usr/include
ln -s c++/v1/cxxabi.h
ln -s c++/v1/__cxxabi_config.h
cd /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator16.4.sdk/usr/include
ln -s c++/v1/cxxabi.h
ln -s c++/v1/__cxxabi_config.h
cd /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS16.4.sdk/usr/include
ln -s c++/v1/cxxabi.h
ln -s c++/v1/__cxxabi_config.h
```
next there's a warning (unused variable) that is treated like an error. We suppress that by commenting line , in `engine/src/build/config/compiler/BUILD.gn`:
```
634:    "-Werror",  # Warnings as errors.
```
